### ISSUE TITLE
exe fails to run after build

### ISSUE THREAD

**Issue by PatrickDattilio** [ExposureSoftware/TEC-Client#71]
After `python setup.py build` running the exe gives the following error:

Traceback (most recent call last):
  File "P:\Programs\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.**dict**)
  File "main.py", line 1, in <module>
  File "c:\python\32-bit\3.4\lib\importlib_bootstrap.py", line 2214, in _find_and_load
  File "c:\python\32-bit\3.4\lib\importlib_bootstrap.py", line 2203, in _find_and_load_unlocked
  File "c:\python\32-bit\3.4\lib\importlib_bootstrap.py", line 1191, in _load_unlocked
  File "c:\python\32-bit\3.4\lib\importlib_bootstrap.py", line 1161, in _load_backward_compatible
AttributeError: 'module' object has no attribute '_fix_up_module'

**Comment by PatrickDattilio** [comment]
I had to install cx_freeze  from here to get this building.

http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze

**Comment by marshall-davis** [comment]
cx_freeze is **incredibly** picky about your environment. It must be compiled with the write libraries.

It's part of why I am afraid to even change dev machines usually.

Chances are anyone who wishes to build this will have to determine the best way for them to install cx_freeze.

**Comment by marshall-davis** [comment]
That being said, I don't think it's an issue in our code. Going to close this issue.

Feel free to reopen if I missed something or you disagree.
